spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/url_shortener?currentSchema=uss
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  server-id: 1

jwt:
  secret: we*B$$!&B@|?:"{_=c=w74fb2n19f~6chapvt2,cq;r3i4jqinoms$%J@&@*J!INY%&D%Vh8hh37dg6gw([]9
  expiration-ms: 3600000