spring:
  application:
    name: url-shortener

  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          default_schema: uss
      show-sql: true

logging:
  level:
    root: INFO
    com.urlshortener.backend: DEBUG